### ISSUE TITLE
Error running witt

### ISSUE THREAD

**Issue by cfjedimaster** [kerryspchang/WITT#1]
Just installed (Windows Subsystem for Linux) and I get:

    /usr/bin/env: ‘node --harmony’: No such file or directory

**Comment by kerryspchang** [comment]
Hi thanks for reporting this. I just updated the git repo. Could you download Witt from here again and `npm install -g` to see if it works? I'm very certain that the bug is due to Linux doesn't support multiple arguments in shebangs, but I don't have a Linux machine now to test it.

**Comment by cfjedimaster** [comment]
Now I get: `Error: Cannot find module 'socket.io'`.

**Comment by kerryspchang** [comment]
The error shows that the socket.io module is not installed. Did you run `npm install`? Try going to the root folder of Witt (where `witt.js` is at) and see if there's a `node_modules` folder that has a `socket.io` folder in it. If not, run `npm install` at the root folder of Witt. That should create `node_modules` that holds a bunch of modules Witt uses, including `socket.io`. You can then run `node ./path/to/witt.js`to run Witt. Please let me know if it works. Thanks.

**Comment by cfjedimaster** [comment]
I did not - I thought you had said to *just* do npm install -g. Trying now.

**Comment by cfjedimaster** [comment]
Ok - that did it. :)

**Comment by kerryspchang** [comment]
:) hope the tool is useful to you. let me know if you want more features
